treolabs/treopim

app/Resources/i18n/de_DE/Global.json, app/Resources/i18n/en_US/Global.json, app/Resources/metadata/clientDefs/Catalog.json, client/modules/pim/src/views/catalog/record/detail.js, client/modules/pim/src/views/catalog/record/list.js
t-75622 add hint to Catalog record delete confirm-modal window
=> t-75622 add hint to Catalog record delete confirm-modal window

app/Resources/metadata/entityDefs/Product.json
add importMultipleField param for productCategories field in Product
=> Add importMultipleField param for productCategories field in Product

app/Listeners/ProductEntity.php
https://github.com/treolabs/treopim/issues/128
=> skip PF attribute hook while removing product

app/Resources/metadata/entityDefs/ProductAttributeValue.json
Added hasCompleteValidation param for value field in ProductAttributeValue
=> Added completeness validation param for value field

app/Listeners/ProductAttributeValueEntity.php
Fixed saving empty attributes old values in Note entity for revision popup panel.
=> fixed empty values in revision popup

app/Resources/metadata/entityDefs/Catalog.json
Removed required param from categories
=> Removed required param from categories

app/Listeners/ProductEntity.php
In Product listener removed check for imported entities when create new Product.
=> removed check for import while create product

app/Listeners/ProductController.php, client/modules/pim/src/views/catalog/record/panels/categories.js, client/modules/pim/src/views/product-image/record/edit.js, client/modules/pim/src/views/product/fields/image.js, client/modules/pim/src/views/product/record/panels/product-categories.js, client/modules/pim/src/views/product/record/panels/product-images.js
1) Fixed promises for Product Image creation.
2) Fixed main image displaying.
3) Fixed images panel displaying when it filtered by scope.
4) Fixed scope and channel fields displaying in images panel.
=> Fixed images panel in Product

app/Listeners/ProductCategoryEntity.php, app/Resources/metadata/clientDefs/Product.json
Added ability linking a product to a category containing child categories
=> Llinking a product to a category containing child categories

app/Resources/metadata/entityDefs/ProductFamilyAttribute.json, client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Added "expandLocales" param to multilang fields while filtering,
Removed "required" param from name field in ProductAttributeValue
=> Added "expandLocales" param to multilang fields while filtering

app/Resources/i18n/de_DE/Category.json, app/Resources/i18n/en_US/Category.json, app/Resources/metadata/entityDefs/Product.json
Added exportMultipleField param for product categories
=> Added translates for catalogs in Category;

client/modules/pim/src/views/product/record/panels/product-categories.js
=> Fixed condition for filter by channel in Categories panel

app/Listeners/ProductEntity.php
* added check for import Product Family in updating Product attributes
=> added check for import product family in product

client/modules/pim/src/views/product/record/panels/product-attribute-values.js, client/modules/pim/src/views/product/record/panels/product-categories.js, client/modules/pim/src/views/product/record/panels/product-images.js
#152
Fixed condition for advanced filters in detail and relationship panels
=> Fixed condition for advanced filters in detail and relationship panels

client/modules/pim/src/views/product-family/record/panels/product-family-attributes.js
Fixed condition for listener in Product Family Attributes panel
#155
=> Fixed condition for listener in Product Family Attributes panel

app/Services/Product.php
* Fixed query for associated products main images when don't get correct images.
=> fixed query for associated products

app/Listeners/ProductEntity.php
=> added check for new entity when change product family

client/modules/pim/src/views/product/record/search.js
Fixed filters for Product page
=> Fixed filters for Product page

app/Resources/metadata/clientDefs/CategoryImage.json, app/Resources/metadata/clientDefs/ProductAttributeValue.json, app/Resources/metadata/clientDefs/ProductCategory.json, app/Resources/metadata/clientDefs/ProductFamilyAttribute.json, app/Resources/metadata/clientDefs/ProductImage.json, app/Resources/metadata/entityDefs/CategoryImage.json, app/Resources/metadata/entityDefs/ProductAttributeValue.json, app/Resources/metadata/entityDefs/ProductCategory.json, app/Resources/metadata/entityDefs/ProductFamilyAttribute.json, app/Resources/metadata/entityDefs/ProductImage.json, composer.json
Required for some fields is determined by dynamic logic
https://github.com/treolabs/treopim/issues/123
=> Changed logic for required fields

app/Resources/metadata/entityDefs/ProductFamilyAttribute.json
In entity "ProductFamilyAttribute" option "noLoad" changed to false
#174
=> In entity "ProductFamilyAttribute" option "noLoad" changed to false

client/modules/pim/src/views/category-image/fields/channels.js, client/modules/pim/src/views/category-image/record/edit.js, client/modules/pim/src/views/product-image/fields/channels.js, client/modules/pim/src/views/product-image/record/edit.js
Fix bug: Changing Scope to IMAGES shows 400 from the product and page: No changes for updating.
=> Fix bug: Changing Scope to IMAGES shows 400 from the product and page: No changes for updating.

client/modules/pim/src/views/product-attribute-value/fields/value-container.js, client/modules/pim/src/views/product/fields/image.js, client/modules/pim/src/views/product/record/detail.js, client/modules/pim/src/views/product/record/panels/product-attribute-values.js, client/modules/pim/src/views/product/record/panels/product-bundles.js, client/modules/pim/src/views/product/record/panels/product-images.js
Fixed attributes saving and validation;
Fixed product images panel displaying;
Removed undefined id in product image field;
Fixed additional data and model defs for attributes;
=> Fixed attributes saving and validation

app/Listeners/ProductEntity.php, app/Listeners/ProductImageEntity.php, app/Services/ProductImage.php
Added sorting ProductImage during him creation
=> Added sorting ProductImage during him creation

app/Listeners/ProductCategoryEntity.php, app/Resources/metadata/clientDefs/Category.json, app/SelectManagers/Category.php, client/modules/pim/src/views/product-category/fields/category.js, client/modules/pim/src/views/product/record/panels/product-categories.js
Removed "hasNoChildCategory" filter for product category
=> Removed "hasNoChildCategory" filter for product category

app/Listeners/AttachmentController.php, app/Resources/i18n/de_DE/Attribute.json, app/Resources/i18n/en_US/Attribute.json, app/Resources/metadata/entityDefs/Attribute.json, app/Resources/metadata/entityDefs/ProductAttributeValue.json, client/modules/pim/src/views/product-attribute-value/fields/value-container.js, client/modules/pim/src/views/product-attribute-value/record/detail-small.js, client/modules/pim/src/views/product-attribute-value/record/detail.js, client/modules/pim/src/views/product-attribute-value/record/edit-small.js, client/modules/pim/src/views/product-attribute-value/record/edit.js, client/modules/pim/src/views/product/record/panels/product-attribute-values.js
=> Added an image type attribute

app/Services/ProductAttributeValue.php
=> value convertation for specified attributes types (int,float,unit)

docs/de/faq/kosten.md, docs/de/faq/produktverwaltung.md
Please, merge, but leave the branch
=> Documents new

client/modules/pim/src/views/product-attribute-value/record/list-in-product.js, client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Fix condition for attributes changing mode method
=> Fix condition for attributes changing mode method

client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Fixed checking for changes before saving attributes
=> Fixed checking for changes before saving attributes

app/Resources/metadata/entityDefs/Product.json, client/modules/pim/src/views/product/fields/image.js, client/modules/pim/src/views/product/record/plate.js
=> Fix incorrect dispay of the images

app/Resources/metadata/entityDefs/Category.json, app/Resources/metadata/entityDefs/PimImage.json, app/Resources/metadata/entityDefs/Product.json
=> Changes concerning "Add/Remove relations"

app/SelectManagers/Product.php
Optimization for category filter at Product list page
=> Optimization for category filter at Product list page

client/modules/pim/src/views/product/record/detail.js
=> Fixed saving for Product

client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Fixed initial attributes for Product Attributes panel in Product
=> Fixed initial attributes for Product Attributes panel in Product

client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Fixed checking for attributes value equality
=> Fixed checking for attributes value equality

app/Resources/metadata/clientDefs/AttributeGroup.json, app/Resources/metadata/clientDefs/Category.json, app/Resources/metadata/clientDefs/Product.json, client/modules/pim/src/views/attribute-group/record/panels/attributes.js
Adaptation for new dragNdrop mechanic in list view
=> Adaptation for new dragNdrop mechanic in list view

app/Resources/metadata/clientDefs/PimImage.json
=> Displaying the main image

app/Migrations/V3Dot10Dot2.php, app/Resources/metadata/entityDefs/AssociatedProduct.json
=> Seaching on the associated product entity list

client/modules/pim/src/views/product/record/detail.js, client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Added changing container for not visible element in showValidationMessage
Fixed filters for attribute groups
=> Fixed filters for attribute groups; added changing container for not visible element in showValidationMessage

app/Resources/metadata/clientDefs/Product.json
Added sorting ProductAttributeValue
https://github.com/treolabs/treopim/issues/238
=> Added sorting ProductAttributeValue

client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Added trigger for collapsing panel
=> Added trigger for collapsing panel

app/Resources/metadata/entityDefs/ProductAttributeValue.json
Corrected sorting for attributeValues after update on a product page
https://github.com/treolabs/treopim/issues/249
=> Corrected sorting for attributeValues after update

app/Services/ProductAttributeValue.php
Fixed display of the decimal values
https://github.com/treolabs/treopim/issues/250
=> Fixed display of the decimal values

client/modules/pim/src/views/product-attribute-value/fields/value-container.js
Added styles for enums values in product attribute values
=> Added styles for enums values in product attribute values

client/modules/pim/res/templates/attribute/fields/type-value/edit.tpl, client/modules/pim/src/views/attribute/fields/type-value.js
=> Fixed arrow

app/Resources/metadata/clientDefs/Channel.json, client/modules/pim/src/views/product-attribute-value/fields/value-container.js
Removed quickCreate for Channel; fixed product attribute value displaying
=> Removed quickCreate for Channel; fixed product attribute value displaying

client/modules/pim/src/views/product/record/panels/product-attribute-values.js
=> Removed old listeners

app/Resources/metadata/clientDefs/Product.json, client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Fixed listeners in Product Attribute Values panel
=> Fixed listeners in Product Attribute Values panel

app/Resources/i18n/de_DE/Global.json, app/Resources/i18n/en_US/Global.json, app/Resources/layouts/AssetRelation/detailSmall.json, app/Resources/metadata/clientDefs/AssetRelation.json, app/Resources/metadata/clientDefs/Product.json, app/Resources/metadata/entityDefs/Asset.json, app/Resources/metadata/entityDefs/AssetRelation.json, app/Resources/metadata/entityDefs/Channel.json, app/Resources/metadata/entityDefs/Product.json, app/Services/Attachment.php, composer.json
Adapted to the Core 3.24 and the module DAM
https://github.com/treolabs/treopim/issues/265
=> Adapted to the Core 3.24 and the module DAM

app/Resources/i18n/de_DE/Global.json, app/Resources/i18n/en_US/Global.json, app/Resources/layouts/Product/relationships.json
Fixed default layout Bottom Panels
=> Fixed default layout Bottom Panels

app/Repositories/ProductFamily.php, app/Resources/metadata/clientDefs/ProductFamily.json, client/modules/pim/src/views/product-family/record/panels/product-family-attributes.js
Add ability to unlink product family attribute. It means that unlinked product family attribute becomes custom products attribute
=> Add ability to unlink product family attribute

app/Migrations/V3Dot11Dot13.php
=> Fixed migration PimImage

app/Migrations/V3Dot11Dot13.php
Fixed migration PimImage to Asset
=> Fixed migration PimImage to Asset

app/Services/RevisionField.php
Fixed display the attribute image in modal window Revisions
=> Fixed display the attribute image in modal window Revisions

client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Fixed attribute group collection options
=> Fixed attribute group collection options

app/Migrations/V3Dot11Dot13.php
Bug fixed related to pimImageChannel migration to Dam
=> Bug fixed related to pimImageChannel migration to Dam

app/Resources/layouts/ProductAttributeValue/listSmall.json, client/modules/pim/src/views/product-attribute-value/fields/attribute-with-required-sign.js, client/modules/pim/src/views/product-attribute-value/record/list-in-product.js
Modified product attribute values panel view
=> Modified product attribute values panel view

app/Migrations/V3Dot11Dot13.php, app/Resources/layouts/AssetRelation/list.json, app/Resources/layouts/AssetRelation/listSmall.json
=> Fixed bugs in Asset Relation

app/Migrations/V3Dot11Dot13.php
Fixed migration main image to down
=> Fixed migration main image to down

app/Listeners/ProductAttributeValueEntity.php
=> Fixed display attribute Image

app/Listeners/AssetRelationEntity.php
Multiple Scope - Channel pictures have the same channel and Main role
https://github.com/treolabs/treopim/issues/332
=> Fixed bug in Asset Relation with Main role

app/Controllers/Channel.php, app/Listeners/ProductController.php, app/Resources/layouts/Channel/listForChannelsInProduct.json, app/Resources/metadata/clientDefs/Product.json, app/Resources/metadata/entityDefs/Channel.json, app/Resources/metadata/entityDefs/Product.json, app/Resources/routes.json, app/Services/Channel.php, client/modules/pim/src/views/channel/record/list-in-product.js, client/modules/pim/src/views/product/record/panels/product-channels.js
Added column Active for Channel in Product
=> Added column Active for Channel in Product

app/Resources/metadata/entityDefs/Channel.json, app/Resources/metadata/entityDefs/Product.json
Active for Channel  default is false
=> Active for Channel  default is false

client/modules/pim/src/views/product/list.js, client/modules/pim/src/views/product/record/search.js
Fixed filters with catalog tree panel
=> Fixed filters with catalog tree panel

app/Listeners/ChannelEntity.php, app/Listeners/ProductEntity.php, app/Services/Channel.php
Set default value in isActive for channel after deleted link
=> Set default value in isActive for channel after deleted link

app/SelectManagers/Product.php
Filter products by category regardless of Scope
https://github.com/treolabs/treopim/issues/364
=> Filter products by category regardless of Scope

client/modules/pim/src/views/channel/record/list-in-product.js
=> Added method for changing mode in isActive field

client/modules/pim/src/views/product-attribute-value/fields/value-container.js, client/modules/pim/src/views/product-attribute-value/record/detail.js, client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Adaptation for Multi-Language 1.14
=> Adaptation for Multi-Language 1.14

app/Resources/layouts/ProductAttributeValue/listSmall.json
=> Changed columns width

app/Migrations/V3Dot10Dot0.php
=> Fixed bugs in migration

app/Resources/i18n/de_DE/ChannelPricing.json, app/Resources/layouts/Product/relationships.json
=> Remove productPrices

client/modules/pim/src/views/product/record/detail.js
=> Fixed Generic Fields filter

app/Migrations/V3Dot10Dot0.php
Fixed migration mainImage and channels for Product and Category
=> Fixed migration mainImage and channels for Product and Category

app/Migrations/V3Dot10Dot0.php
Fixed migration for pimImages to down
=> Fixed migration for pimImages to down

app/Module.php
Fixed validation error while creating multi-lang attribute of type Enum or Multi-Enum;
https://github.com/treolabs/treopim/issues/398
=> Fixed validation error while creating multi-lang attribute of type Enum or Multi-Enum;

app/Module.php
Fixed validation multilang ProductAttrivuteValue
=> Fixed validation multilang ProductAttrivuteValue

app/Resources/metadata/clientDefs/Product.json, client/modules/pim/src/views/product/record/panels/product-categories.js
78363
Corrected displaying of product categories panel
=> Corrected displaying of product categories panel

client/modules/pim/src/views/product/record/detail.js
Fixed advanced filter for multi-language & generic fields
=> Fixed advanced filter for multi-language & generic fields

app/Resources/metadata/app/clientClassReplaceMap.json, client/modules/pim/src/views/category/record/detail.js, client/modules/pim/src/views/record/detail.js
76879 
Fixed an issue when "edit mode" was shut off after incorrect save
=> Fixed an issue when "edit mode" was shut off after incorrect save

client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Event for complete-side update
=> Event for complete-side update

app/Resources/metadata/entityDefs/Channel.json, client/modules/pim/src/views/product/record/panels/product-attribute-values.js
Fixed validation in product attribute values panel
=> Fixed validation in product attribute values panel

app/Event.php, composer.json
Added dependence treolabs/completeness-common
=> Added dependence treolabs/completeness-common

app/Services/Product.php
Fixed bug when creating a product on a newly installed system
=> Fixed bug when creating a product on a newly installed system

app/Resources/i18n/de_DE/Product.json
=> Removed old translates

app/Migrations/V3Dot12Dot3.php
Added migration for completeness
=> Added migration for completeness

app/Listeners/AssetRelationEntity.php, app/Module.php, client/modules/pim/src/views/asset-relation/fields/channels.js
Fixed bug with field Scope for assetRelation
=> Fixed bug with field Scope for assetRelation

app/Listeners/AssetRelationEntity.php, app/Services/Product.php
Moved the isMainRole method in Pim\Services\Product
https://github.com/treolabs/treopim/issues/428
=> Moved the isMainRole method in Pim\Services\Product

app/Listeners/ProductFamilyEntity.php
Removed ProductFamilyAttribute after deleting ProductFamily
=> Removed ProductFamilyAttribute after deleting ProductFamily

app/Listeners/AbstractEntityListener.php, client/modules/pim/src/views/fields/code-from-name.js
79310
changed code field validation
=> changed code field validation

client/modules/pim/src/views/channel/record/list-in-product.js
=> Fixed bug in show more

app/Listeners/AssetEntity.php
Remove main image after remove Asset
=> Remove main image after remove Asset

client/modules/pim/src/views/product/record/plate-item.js
78397
Fixed bug with navigation between products
#187
=>  Fixed bug with navigation between products

app/Migrations/V3Dot12Dot0.php
Fixed channels migrations for PimImage
=> Fixed channels migrations for PimImage

app/Module.php, app/Resources/i18n/de_DE/Global.json, app/Resources/i18n/en_US/Global.json
New label for side image panel
=> New label for side image panel

client/modules/pim/src/views/product-attribute-value/fields/attribute.js
79916
Added displaying of multilang fields when adding multilang product attribute
=> Added displaying of multilang fields when adding multilang product attribute

app/Listeners/AttributeGroupEntity.php, app/Resources/i18n/de_DE/Attribute.json, app/Resources/i18n/en_US/Attribute.json, app/Resources/metadata/clientDefs/AttributeGroup.json, client/modules/pim/src/views/attribute/modals/select-records-in-attribute-group.js
Added filtering for attributes linking in attribute group
=> Added filtering for attributes linking in attribute group

client/modules/pim/src/views/product-attribute-value/modals/detail.js
78685
Fixed editing method for Image/Unit attributes
#232
=> Fixed editing method for Image/Unit attributes

client/modules/pim/src/views/product/record/panels/product-attribute-values.js
78628
Fixed updating of product attribute values after changes
#221
=> Fixed updating of product attribute values after changes

app/Resources/metadata/clientDefs/Category.json, app/Resources/metadata/clientDefs/Product.json, app/SelectManagers/Product.php, client/modules/pim/src/views/category/record/panels/category-products.js
78348 
Added the ability to link products to categories from the category page
=> Added the ability to link products to categories from the category page

client/modules/pim/src/views/product-attribute-value/fields/attribute.js
81300
refactoring of multi language attributes logic
=> refactoring of multi language attributes logic

client/modules/pim/src/views/product-attribute-value/fields/value-container.js, client/modules/pim/src/views/product-attribute-value/record/detail.js
81300
Fixed bug with selecting of enum value
Fixed read-only setting for enum and multi-enum attributes
=> Fixed read-only setting for enum and multi-enum attributes

client/modules/pim/src/views/product-attribute-value/record/detail.js
79916
Fixed bug with displaying of empty values for multi language enum
=> Fixed bug with displaying of empty values for multi language enum

client/modules/pim/src/views/record/panels/pim-images.js
78638
Added filtering with using the scope on the product page for images
#222
=> Added filtering with using the scope on the product page for images

client/modules/pim/src/views/attribute/fields/attribute-group.js
81087 
Added read-only status for attribute group
=> Added read-only status for attribute group

client/modules/pim/src/views/product/record/panels/product-attribute-values.js
81500
Removed default values for enum
=> Removed default values for enum

client/modules/pim/res/templates/product/record/search.tpl
80868 
Now length of the search field in modal dialog will be the entire available width
=> Now length of the search field in modal dialog will be the entire available width
